services:
  web:
    build: .
    ports:
      - "8082:80"  # ubah port host jadi 8082
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gojo_db
    ports:
      - "3307:3306"  # ubah port host jadi 3307
