version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"  # ← kembali ke 8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gojo_db
    ports:
      - "3307:3306"  # hindari bentrok dengan MySQL lokal
