version: '3.8'

services:
  web:
    image: jiklii/gojo-app:latest
    ports:
      - "8080:80"  

    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=gojo_db
    volumes:
      - ./:/var/www/html
    restart: always

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: gojo_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
